### ISSUE TITLE
[Allocation] Project application, acceptance, allocation and receiving grants

### ISSUE THREAD

**Issue by bitbeckers** [grants-stack-frontier/allo-v2#15]
- [x] #17

Most lifecycle features should be covered in #1 and #5 

Check and test on:

- [x] Project is part of registry
- [x] Project can receive Hedgey
- [x] Project can not reapply after cancellation
- [x] Project must be approved before receiving funding
